name: cristalyse
description: "Cristalyse is a high-performance data visualization library for Dart/Flutter that implements grammar of graphics principles with native rendering capabilities."
version: 0.9.3
homepage: https://github.com/rudi-q/cristalyse
repository: https://github.com/rudi-q/cristalyse
issue_tracker: https://github.com/rudi-q/cristalyse/issues
documentation: https://github.com/rudi-q/cristalyse#readme

screenshots:
  - description: 'Dual Y-axis Example with custom theme'
    path: example/screenshots/cristalyse_dual_axis_chart.gif
  - description: 'Stacked Bar Plot Example with custom theme'
    path: example/screenshots/cristalyse_stacked_bar_chart.gif
  - description: 'Grouped Bar Plot Example with custom theme'
    path: example/screenshots/cristalyse_grouped_bar_chart.gif
  - description: 'Horizontal Bar Plot Example with custom theme'
    path: example/screenshots/cristalyse_horizontal_bar_chart.gif
  - description: 'Scatter Plot Example with custom theme'
    path: example/screenshots/cristalyse_scatter_plot.gif
  - description: 'Line Plot Example with custom theme'
    path: example/screenshots/cristalyse_line_chart.gif
  - description: 'Bar Plot Example with custom theme'
    path: example/screenshots/cristalyse_bar_chart.gif
  - description: 'Complete Guide available at docs.cristalyse.com'
    path: example/screenshots/documentation.png

topics:
  - data-visualization
  - charts
  - flutter-charts
  - plotting
  - analytics

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
